# Generated by Django 6.0.2 on 2026-03-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='fecha_limite',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
