# Generated by Django 6.0.2 on 2026-03-06 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_alter_activity_fecha_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='curso',
            field=models.CharField(choices=[('calculo', 'Cálculo'), ('algebra', 'Álgebra Lineal'), ('estadistica', 'Estadística'), ('fisica', 'Física'), ('quimica', 'Química'), ('biologia', 'Biología'), ('programacion', 'Programación'), ('estructuras', 'Estructuras de Datos'), ('bases_datos', 'Bases de Datos'), ('redes', 'Redes de Computadores'), ('sistemas_op', 'Sistemas Operativos'), ('ingenieria_sw', 'Ingeniería de Software'), ('economia', 'Economía'), ('administracion', 'Administración'), ('contabilidad', 'Contabilidad'), ('derecho', 'Derecho'), ('ingles', 'Inglés'), ('humanidades', 'Humanidades'), ('etica', 'Ética'), ('otro', 'Otro')], default='otro', max_length=30),
        ),
    ]
